/// all xxxRep should be private 
///|
type! LamRep Arrow[Term, Term]
type! FixedArrayRep FixedArray[Term]
///|
type! IntRep Int

///|
type! CharRep Char

///|
type! ByteRep Byte

///|
type! BytesRep Bytes

///|
type! Int64Rep Int64

///|
type! UIntRep UInt

///|
type! UInt64Rep UInt64

///|
type! FloatRep Float

///|
type! UnitRep Unit

///|
type! BoolRep Bool

///|
type! StringRep String
